spring:
  application:
    name: ms-pagos
  profiles:
    default: dev

logging:
  level:
    root: INFO

springdoc:
  api-docs:
    enabled: true

  swagger-ui:
    enabled: true
    path: /swagger-ui.html

  packages-to-scan: com.clinic.ms_pagos.controller